services:
  postgres:
    image: postgres:18
    container_name: sppr-orm-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_secret
      POSTGRES_DB: sppr_orm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d sppr_orm"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8
    container_name: sppr-orm-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
